cuboid:

  d435i:
    pose: [0, 0, 0, 1, 0, 0, 0]
    dims: [0.09, 0.027, 0.026]

  connector:
    pose: [0, 0, 0, 1, 0, 0, 0]
    dims: [0.065, 0.025, 0.04]

  usb:
    pose: [0, 0, 0, 1, 0, 0, 0]
    dims: [0, 0, 0]